services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: gamebuilds
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "100.77.136.106:8088:80"
    volumes:
      - /mnt/media/game-builds:/srv
      - /srv/docker/gamebuilds/database.db:/database.db
      - /srv/docker/gamebuilds/settings.json:/settings.json
