---

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hourCycle: h12

- resources:
    label: HopeLab
    expanded: false
    cpu: true
    memory: true
    cputemp: true
    uptime: true
    refresh: 1000

- resources:
    label: Opti
    expanded: true
    disk:
      - /

- resources:
    label: External
    expanded: true
    disk:
      - /mnt/media

- openmeteo:
    label: Providence
    latitude: 41.8240
    longitude: -71.4128
    timezone: America/New_York
    units: imperial
    cache: 5
