services:
  porkbun-ddns:
    image: mietzen/porkbun-ddns:latest
    container_name: porkbun-ddns
    restart: unless-stopped

    environment:
      APIKEY: ${APIKEY}
      SECRETAPIKEY: ${SECRETAPIKEY}
      DOMAIN: "kai.coach"
      SUBDOMAINS: "jellyfin,seerr,immich,home,status,grafana,n8n,address"
      INTERVAL: "300"
